In [1]:
import numpy as np

#<font color="cyan">Input</font>

In [2]:
x = np.array([[20, 17, 32, 42, 65],
              [13, 65, 96, 53, 21],
              [45, 63, 74, 38, 64],
              [23, 76, 40, 34, 26],
              [14, 66, 78, 49, 23]])

#<font color="orange">Batch Noramlization</font>

In [9]:
mean = x.mean(axis=0)
var = x.var(axis=0)
std = np.sqrt(var)
batch_noramlization = (x - mean) / std
np.set_printoptions(precision=2)
print("Batch Normalization : \n", batch_noramlization)

Batch Normalization : 
 [[-0.26 -1.95 -1.32 -0.17  1.25]
 [-0.86  0.37  1.32  1.41 -0.93]
 [ 1.89  0.27  0.41 -0.75  1.2 ]
 [ 0.    0.9  -0.99 -1.32 -0.68]
 [-0.78  0.42  0.58  0.83 -0.83]]


#<font color="orange">Layer Noramlization</font>

In [10]:
mean = x.mean(axis=1)
var = x.var(axis=1)
std = np.sqrt(var)
layer_noramlization = (x - mean) / std
np.set_printoptions(precision=2)
print("Layer Normalization : \n", layer_noramlization)

Layer Normalization : 
 [[-0.88 -1.08 -1.87  0.12  0.78]
 [-1.28  0.51  2.96  0.69 -1.02]
 [ 0.56  0.44  1.3  -0.09  0.74]
 [-0.7   0.87 -1.27 -0.3  -0.82]
 [-1.22  0.54  1.6   0.48 -0.94]]
